### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-tracking#14]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] stock_barcode_reader
- [ ] stock_inventory_sequence
- [ ] stock_move_packaging
- [ ] stock_move_split_default
- [ ] stock_packaging_usability
- [ ] stock_packaging_usability_ul
- [ ] stock_product_category_tracked
- [ ] stock_tracking_add_move
- [ ] stock_tracking_add_remove
- [ ] stock_tracking_add_remove_pack
- [ ] stock_tracking_child
- [ ] stock_tracking_extended
- [ ] stock_tracking_prodlot
- [ ] stock_tracking_reopen
- [ ] stock_tracking_state
- [ ] stock_tracking_swap
- [ ] stock_tracking_swap_pack
