### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-tracking#9]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] stock_product_category_tracked
- [ ] stock_inventory_sequence
- [ ] stock_tracking_extended
- [ ] stock_tracking_state
- [ ] stock_tracking_child
- [ ] stock_packaging_usability_ul
- [ ] stock_packaging_usability
- [ ] stock_tracking_swap
- [ ] stock_move_split_default
- [ ] stock_move_packaging
- [ ] stock_tracking_add_move
- [ ] stock_tracking_prodlot
- [ ] stock_barcode_reader
- [ ] stock_tracking_swap_pack
- [ ] stock_tracking_add_remove_pack
- [ ] stock_tracking_add_remove
- [ ] stock_tracking_reopen

**Comment by tbaden** [comment]
Are these modules still viable or did odoo add these features into the core? Thinking about some migration work.

**Comment by pedrobaeza** [comment]
For version 9? I don't advise you to do it as this version is deprecated and not too much people implemented it. Better to focus on migration to 12.0 IMO.

**Comment by pedrobaeza** [comment]
Any way, these modules are not very used per se or they have been replaced by others. In fact, I don't know the real usage of this repo.

**Comment by rousseldenis** [comment]
@pedrobaeza These are modules related to packing operations.

I know this is an unpopular repo and indeed some mdoules are present in warehouse or workflow one instead of here.

I'll try to dig up some and communicate on this. That could help not having too much modules in those ones.

**Comment by pedrobaeza** [comment]
Thanks for the explanation, although I still don't get the general picture/need for this specific one, but let's dig in this next week.
